server:
  port: 8082
spring:
  application:
    name: provide
  devtools:
    restart:
      enabled: false
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/own?useSSL=false&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: laij082699
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 5000
          enabled: true
        wall:
          db-type: mysql
          enabled: true
          config:
            delete-allow: true
            drop-table-allow: false
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    cache-enabled: true
    use-column-label: true
    auto-mapping-behavior: full
  type-aliases-package: com.springcloud.entity
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com.springcloud.provide: debug

eureka:
  client:
    service-url:
      defaultZone: http://eureka.server7001.com:7001/eureka/,http://eureka.server7002.com:7002/eureka/,http://eureka.server7003.com:7003/eureka/
  instance:
    instance-id: eureka-client-8082
    prefer-ip-address: true

info:
  app.name: spring-cloud-eureka-client-8082
  descripe: "8082服务,Eureka客户端"
